<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>175940f9-a2ef-495f-8e99-bfc78d03a43e</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="7.0.20" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.4.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\WebApiLivraria.Application\WebApiLivraria.Application.csproj" />
	</ItemGroup>

</Project>
