<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.69.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebApiLivraria.Domain\WebApiLivraria.Domain.csproj" />
    <ProjectReference Include="..\WebApiLivraria.Infrastructure\WebApiLivraria.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UseCases\Avaliacao\Editar\" />
  </ItemGroup>

</Project>
